"""add payment code

Revision ID: 77962abb2f53
Revises: 0b6d13f68a51
Create Date: 2024-05-20 17:29:21.880500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77962abb2f53'
down_revision: Union[str, None] = '0b6d13f68a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('payment_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'payment_code')
    # ### end Alembic commands ###
